name: env
channels:
  - defaults
dependencies:
  - numpy=1.26.0
  - pandas=2.1.1
  - pip=23.2.1
  - python=3.10
  - tqdm=4.65.0
  - pip:
      - azureml-mlflow==1.53.0
      - jupyterlab==4.0.7
      - mlflow==2.7.1
      - pre-commit==3.5.0
      - typer==0.9.0
      - pycocotools==2.0.7
      - torch==1.12.1
      - torchvision==0.13.1
      - torchaudio==0.12.1
      - pytorch-lightning==2.0
      - pytorch_lightning
      - tsdb==0.2.1
      - rich==13.3.5
      - Sphinx==7.3.7
      - sphinx_rtd_theme==2.0.0